### ISSUE TITLE
Feature : Github Actions를 활용한 CI/CD 

### ISSUE THREAD

**Issue by cmun2** [cupicks/cupicks-fe#211]
### 해당 기능

React  애플리케이션의 CI/CD

Github Actions가 특정 브랜치의 변경을 감시하다가, 변경이 감지되면 Workflow 프로세스를 실행하고, 이때 빌드과정과 S3 배포 과정이 실행된다.
### 작업 내용

1. Github에서 배포를 위해 AWS S3로 접근하기 위해서는 권한이 필요하다.

간단하게 S3에 파일을 업로드할 수 있는 권한을 가진 사용자를 추가하고, Github는 사용자의 Access Key 정보를 이용해서 S3로의 권한을 얻을 수 있다.

우선 AWS IAM에서 사용자 추가를 눌러 임의의 이름을 설정한 후 아래와 같이 AWS 자격 증명 유형으로 액세스 키-프로그래밍 방식 액세스를 선택한다.

2. Workflow 설정(Github Actions 내 방식)
```
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Node Modules
      run: npm ci
    
    - name: Build
      run: npm run build --if-present
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
```

3. Github Repository의 Setting 페이지의 Secrets>Actions에서 Add a new secret을 통해 각각 AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY라는 이름으로 Access Key ID와 Secret Access Key 정보를 저장한다.

**Comment by cmun2** [comment]
# 1. AWS IAM 설정
## **사용자 이름 입력(자유) / 엑세스 키 - 프로그래밍 방식 엑세스 체크 (CI/CD 서버의 CLI 환경에서 AWS 접속 할 유저 만드는 것)**
![image](https://user-images.githubusercontent.com/66786557/192520112-b56bb180-fba1-4cb2-98ad-183566d1228d.png)

## **AmazonS3FullAccess 체크 / (다음 태그 설정 안해도 됨)**

![image](https://user-images.githubusercontent.com/66786557/192521025-380818a6-1f6d-41b3-a2ed-58cdcaca8b29.png)

## **태그추가 기능(Skip)**
![image](https://user-images.githubusercontent.com/66786557/192521525-72b4f550-4e90-4b1c-881a-59eb66043290.png)

## **속성 값 넣은 것들 확인**
![image](https://user-images.githubusercontent.com/66786557/192521805-a18b0b45-dd71-4c79-bced-3896afb383fc.png)

## **사용자 추가 성공 후, 엑세스 키 ID와 비밀 엑세스 키를 저장(.csv 다운로드 가능) 비밀 엑세스키 노출 X**
![image](https://user-images.githubusercontent.com/66786557/192522951-76204ee5-6df1-4ca5-9b04-afd52580014b.png)

**Comment by cmun2** [comment]
# 2. Workflow 설정

## Github Actions 클릭
![image](https://user-images.githubusercontent.com/66786557/192692947-f3282924-d886-4c8a-95e7-372813de369c.png)

## Node.js로 Configure 만들기
![image](https://user-images.githubusercontent.com/66786557/192693054-a0cb137e-2ffe-41fa-a4ea-b658212d7b6f.png)

## main.yml 생성
![image](https://user-images.githubusercontent.com/66786557/192693220-b851be2e-4e54-4a17-81b0-825d97dca764.png)

코드 입력(+설명추가)
```
#github action 이름(+무작위로 설정가능)
name: release

#push하거나 PR을 날렸을시 github actions가 일어날 branch 설정 
on:
  push:
    branches: 
      - release
  pull_request:
    branches: 
      - release

#build를 ubuntu의 가장 최신 버전으로 실행
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # 소스를 가져옵니다
        - name: Checkout source code
          uses: actions/checkout@v2

        #실행속도를 빠르게 하기 위해 설치된 node 모듈을 캐시하도록 설정
        - name: Cache node modules
          uses: actions/cache@v2
          with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  ${{ runner.os }}-node-

        # 모듈 설치
        - name: Install Dependencies
          run: npm ci

        #env 설정(VITE API 서버)          
        - name: Generate Environment Variable Files for Production
          run: /
            echo "VITE_SERVER_URL=$VITE_SERVER_URL" >> .env.production
          env:
            VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

        #빌드 수행
        - name: Build
          run: npm run build 

         #배포 수행
        - name: Deploy
          env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

          run: |
              aws s3 cp \
              --recursive \
              --region ap-northeast-2 \
              build s3://cupick.co
              
        #배포 후 Cloudfront 캐시 무효화 전체 실행 
        - name: Invalidate CloudFront Cache
          run: aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"
```

## vscode내 생성 방식( .github폴더안에  workflows 폴더안에 main.yml 폴더 직접생성)
![image](https://user-images.githubusercontent.com/66786557/192693364-29ff4a92-9adb-4988-87a4-d026379f3b0a.png)
![image](https://user-images.githubusercontent.com/66786557/192693600-22711136-90d3-4427-b252-1f23ad0094ce.png)
