### ISSUE TITLE
Bug : CI/CD 수행 중 에러

### ISSUE THREAD

**Issue by cmun2** [cupicks/cupicks-fe#233]
### 한 일

Github Actions 수행 중 npm run build에서 에러 발견  

### 에러 내용

![image](https://user-images.githubusercontent.com/66786557/192768854-3205da0e-9bad-4ba8-a9c7-2f8b19da2d94.png)

### 조치 사항

로컬에서 npm run build 수행시 잘 build가 되지만 Github Actions 내에서는 build과정 중 에러가 난다.
![image](https://user-images.githubusercontent.com/66786557/192769255-12e177bd-5fe2-4728-a97b-3eaf8d46aace.png)

**Comment by cmun2** [comment]
# 조치사항

## 경로 에러
- 해당에러가 발견되는 지점이 resolve components의 경로에서 발견되어 확인을해보니 대문자/소문자가 서로 안맞는 현상이 있었습니다. 
- 리액트의 특성상 대소문자 구분 없이 인식을 하여 빌드가 되어 로컬에서는 정상적으로 빌드가 되었지만 Github Actions내에서는 에러로 감지하는 현상이 있었습니다. 
- 해당 문구를 대문자로 고치고 Build 부분을 해결 하였습니다

**Comment by cmun2** [comment]
#Invalidation 부분 에러 발생
![github action error1](https://user-images.githubusercontent.com/66786557/192941139-7578542b-dd1c-471f-b842-a8a83afeaf53.PNG)

**Comment by cmun2** [comment]
# Invalidation 무효화 성공
![image](https://user-images.githubusercontent.com/66786557/193083409-b6577b4a-d461-4746-a5b2-ee79ff41f7d0.png)

```
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cachce node_modules
        uses: actions/cache@v2
        id: node-cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install node_modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Generate Environment Variable Files for Production
        run: |
          pwd
            cd /home/runner/work/cupicks-fe/cupicks-fe
            touch .env
            echo VITE_SERVER_URL=${{secrets.VITE_SERVER_URL}} >> .env
      - name: Build
        run: |
          cd /home/runner/work/cupicks-fe/cupicks-fe
          npm run build
          
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true

        run: |
          aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          dist s3://cupick.co
          
      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"
```
